# Dockerfile for serving the frontend with Nginx
FROM nginx:alpine
# Copy the built assets from the local dist directory to the Nginx html directory
COPY ./dist /var/www/html/dist
# Copy the custom Nginx configuration
COPY docker/nginx.container.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
